### ISSUE TITLE
Add support for negative cds start HGVS notation with offset?

### ISSUE THREAD

**Issue by creisle** [bcgsc/pori_graphkb_parser#5]
A negative start value with an offset for a cds variant  results in a parsing error currently. Is this valid HGVS? If so please add support for this notation

Examples
- `CXorf58:c.-20-1G>C`
- `BTN3A2:c.-42+1G>A`

**Comment by lmwilliamson11** [comment]
a negative start value for cds notation is a valid HGVS notation based on the numbering documentation on the hgvs website https://varnomen.hgvs.org/bg-material/numbering/
"untranslated region (UTR)
nucleotides upstream (5’) of the ATG-translation initiation codon (start) are marked with a “-” (minus) and numbered c.-1, c.-2, c.-3, etc. (i.e. going further upstream)
nucleotides downstream (3’) of the translation termination codon (stop) are marked with a “*” (asterisk) and numbered c.*1, c.*2, c.*3, etc. (i.e. going further downstream)
there is no nucleotide c.0."

**Comment by creisle** [comment]
The negative start is ok. I am just not sure how it can be combined with the offset value. generally the +/- are used to give notation relative to a position on the transcript I thought

**Comment by lmwilliamson11** [comment]
from the Q&A on that page
"c.-106+2T>A is a variant in an intron in the 5’UTR (upstream of the translation initiation site)
since nucleotide “c.-106” has a “-” prefix it is located 5’ of the ATG translation initiation codon and since it is followed by “+” and a second number (“2”) the nucleotide is in the 5’ half of an intron"
